name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Start xcodebuild test
      run: xcodebuild clean test -scheme AccessToInsight -project AccessToInsight.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.4' 